"""Defines rodents constants."""

from etils import epath

RODENT_PATH = epath.Path(__file__).parent

RODENT_XML_PATH = RODENT_PATH / "xmls" / "rodent.xml"
RODENT_BOX_FEET_PATH = RODENT_PATH / "xmls" / "rodent_box_feet.xml"
RODENT_FULL_COLLISION_XML = RODENT_PATH / "xmls" / "rodent_full_collisions.xml"
RODENT_NO_TAIL_COLLISION_XML = RODENT_PATH / "xmls" / "rodent_no_tail_collisions.xml"
ARENA_XML_PATH = RODENT_PATH / "xmls" / "arena.xml"
WHITE_ARENA_XML_PATH = RODENT_PATH / "xmls" / "white_arena.xml"
IMITATION_REFERENCE_PATH = RODENT_PATH / "reference_data" / "reference_clips.h5"

END_EFFECTORS = ["lower_arm_R", "lower_arm_L", "foot_R", "foot_L", "skull"]
TOUCH_SENSORS = ["palm_L", "palm_R", "sole_L", "sole_R"]
BODIES = [
    "torso",
    "pelvis",
    "upper_leg_L",
    "lower_leg_L",
    "foot_L",
    "upper_leg_R",
    "lower_leg_R",
    "foot_R",
    "skull",
    "jaw",
    "scapula_L",
    "upper_arm_L",
    "lower_arm_L",
    "finger_L",
    "scapula_R",
    "upper_arm_R",
    "lower_arm_R",
    "finger_R",
]
JOINTS = [
    "vertebra_1_extend",
    "vertebra_2_bend",
    "vertebra_3_twist",
    "vertebra_4_extend",
    "vertebra_5_bend",
    "vertebra_6_twist",
    "hip_L_supinate",
    "hip_L_abduct",
    "hip_L_extend",
    "knee_L",
    "ankle_L",
    "toe_L",
    "hip_R_supinate",
    "hip_R_abduct",
    "hip_R_extend",
    "knee_R",
    "ankle_R",
    "toe_R",
    "vertebra_C1_extend",
    "vertebra_C1_bend",
    "vertebra_C2_extend",
    "vertebra_C2_bend",
    "vertebra_C3_extend",
    "vertebra_C3_bend",
    "vertebra_C4_extend",
    "vertebra_C4_bend",
    "vertebra_C5_extend",
    "vertebra_C5_bend",
    "vertebra_C6_extend",
    "vertebra_C6_bend",
    "vertebra_C7_extend",
    "vertebra_C9_bend",
    "vertebra_C11_extend",
    "vertebra_C13_bend",
    "vertebra_C15_extend",
    "vertebra_C17_bend",
    "vertebra_C19_extend",
    "vertebra_C21_bend",
    "vertebra_C23_extend",
    "vertebra_C25_bend",
    "vertebra_C27_extend",
    "vertebra_C29_bend",
    "vertebra_cervical_5_extend",
    "vertebra_cervical_4_bend",
    "vertebra_cervical_3_twist",
    "vertebra_cervical_2_extend",
    "vertebra_cervical_1_bend",
    "vertebra_axis_twist",
    "vertebra_atlant_extend",
    "atlas",
    "mandible",
    "scapula_L_supinate",
    "scapula_L_abduct",
    "scapula_L_extend",
    "shoulder_L",
    "shoulder_sup_L",
    "elbow_L",
    "wrist_L",
    "finger_L",
    "scapula_R_supinate",
    "scapula_R_abduct",
    "scapula_R_extend",
    "shoulder_R",
    "shoulder_sup_R",
    "elbow_R",
    "wrist_R",
    "finger_R",
]
